name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.6'
          architecture: 'x64'

      - name: "Prepare env"
        run: "pip install -U pytest"

      - name: Run Unit Tests
        run: "pytest -v"
